### ISSUE TITLE
/etc/eks/bootstrap.sh fails ungracefully if instance type is unknown

### ISSUE THREAD

**Issue by mcasperson** [awslabs/amazon-eks-ami#49]
The code 
```
MAX_PODS=$(grep $INSTANCE_TYPE $MAX_PODS_FILE | awk '{print $2}')
```
will fail if /etc/eks/eni-max-pods.txt does not list the instance type, and exit immediately. This means the kubelet service is never configured properly and the instance is left in a half configured state.

While there is already an issue open to support additional instance types, it would be nice if /etc/eks/bootstrap.sh could at least warn users that an unknown type was used and that the worker is left in an inconsistent state. Right now the only way to determine this is to run through the script line by line to try and work out what is going on.

**Comment by HenryCook** [comment]
Just wanted to echo what @mcasperson has raised as I have been scratching my head due to the script failing silently.

We had been trying to test with `t3.medium` instances however as they are not in `/etc/eks/eni-max-pods.txt` the script would fail with exit status 1 but with no indication as to why in `/var/log/cloud-init.log`:

```
Sep 13 13:35:01 cloud-init[3421]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=True, capture=False)
Sep 13 13:35:04 cloud-init[3421]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Sep 13 13:35:04 cloud-init[3421]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 860, in runparts
    subp(prefix + [exe_path], capture=False, shell=True)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2053, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-001']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
Sep 13 13:35:04 cloud-init[3421]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Sep 13 13:35:04 cloud-init[3421]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
Sep 13 13:35:04 cloud-init[3421]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Sep 13 13:35:04 cloud-init[3421]: util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 798, in _run_modules
    freq=freq)
  File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 867, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 1 attempted commands
```

An error message would be really useful going forward.

**Comment by micahhausler** [comment]
Thanks for reporting this, we’ll get it fixed!
