### ISSUE TITLE
`sandbox-image.service` is failing to pull image.

### ISSUE THREAD

**Issue by jihed** [awslabs/amazon-eks-ami#831]
**What happened**:
The `sandbox-image` service unit is failing to fetch images which causing the `kubelet` to fail. On the other hand, the `pull-sanbox-image.sh` bash script is working fine manually. 

The cluster is an EKS `1.21.5` working behind a proxy which is also configured on contaienrd.service.

```[root@ip-44-130-26-16 ~]# systemctl status sandbox-image.service -l
● sandbox-image.service - pull sandbox image defined in containerd config.toml
   Loaded: loaded (/etc/systemd/system/sandbox-image.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2021-12-15 10:22:25 UTC; 2min 45s ago
  Process: 1052 ExecStart=/etc/eks/containerd/pull-sandbox-image.sh (code=exited, status=2)
 Main PID: 1052 (code=exited, status=2)

Dec 15 10:22:25 ip-44-130-26-16 pull-sandbox-image.sh[1052]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/command.go:329 +0x87f
Dec 15 10:22:25 ip-44-130-26-16 pull-sandbox-image.sh[1052]: github.com/containerd/containerd/vendor/github.com/urfave/cli.Command.Run(0x5640c79439ec, 0x6, 0x0, 0x0, 0x5640c82e7300, 0x2, 0x2, 0x5640c794b50f, 0xd, 0x0, ...)
Dec 15 10:22:25 ip-44-130-26-16 pull-sandbox-image.sh[1052]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/command.go:102 +0xa28
Dec 15 10:22:25 ip-44-130-26-16 pull-sandbox-image.sh[1052]: github.com/containerd/containerd/vendor/github.com/urfave/cli.(*App).Run(0xc00032a380, 0xc0000b8000, 0x9, 0x9, 0x0, 0x0)
Dec 15 10:22:25 ip-44-130-26-16 pull-sandbox-image.sh[1052]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/app.go:276 +0x7d4
Dec 15 10:22:25 ip-44-130-26-16 pull-sandbox-image.sh[1052]: main.main()
Dec 15 10:22:25 ip-44-130-26-16 pull-sandbox-image.sh[1052]: github.com/containerd/containerd/cmd/ctr/main.go:37 +0x125
Dec 15 10:22:25 ip-44-130-26-16 systemd[1]: Failed to start pull sandbox image defined in containerd config.toml.
Dec 15 10:22:25 ip-44-130-26-16 systemd[1]: Unit sandbox-image.service entered failed state.
Dec 15 10:22:25 ip-44-130-26-16 systemd[1]: sandbox-image.service failed.
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
` systemctl start sandbox-image.service`

**Anything else we need to know?**:

**Environment**:
```
- AWS Region: eu-central-1
- Instance Type(s): t3.large, m5.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.4"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): "1.21"
- AMI Version: amazon-eks-node-1.21-v20211206 (ami-02b3f04ab50ffd9f1)
- Kernel (e.g. `uname -a`): Linux ip-44-130-26-16 5.4.156-83.273.amzn2.x86_64 # 1 SMP Sat Oct 30 12:59:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Release information (run `cat /etc/eks/release` on a node):
SE_AMI_ID="ami-051e829ae81b0b8db"
BUILD_TIME="Mon Dec  6 20:08:18 UTC 2021"
BUILD_KERNEL="5.4.156-83.273.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
This looks like a different issue from #795, which is resolved by #823.

Can you provide some more information about your proxy setup? How are you configuring your instances to use it?

**Comment by jihed** [comment]
````sudo mkdir -p /etc/systemd/system/containerd.service.d
tee <<EOF /etc/systemd/system/containerd.service.d/http-proxy.conf >/dev/null
[Service]
EnvironmentFile="HTTP_PROXY=$PROXY"
EOF

tee <<EOF /etc/systemd/system/containerd.service.d/no-proxy.conf >/dev/null
[Service]
EnvironmentFile="NO_PROXY=$NO_PROXY"
EOF

mkdir -p /etc/systemd/system/kubelet.service.d
tee <<EOF /etc/systemd/system/kubelet.service.d/proxy.conf >/dev/null
[Service]
EnvironmentFile=/etc/environment
EOF```

This is part of the userdata on LT. The script `pull-sanbox-images.sh` exected correctly manually.

**Comment by cartermckinnon** [comment]
Your service unit overrides for `containerd` should use the `Environment` directive (instead of `EnvironmentFile`) to set `HTTP_PROXY` and `NO_PROXY`.

**Comment by jihed** [comment]
```sudo mkdir -p /etc/systemd/system/containerd.service.d
tee <<EOF /etc/systemd/system/containerd.service.d/http-proxy.conf >/dev/null
[Service]
Environment="HTTP_PROXY=$PROXY"
EOF

tee <<EOF /etc/systemd/system/containerd.service.d/no-proxy.conf >/dev/null
[Service]
Environment="NO_PROXY=$NO_PROXY"
EOF`` 

The sandbox-image service is failing: 
```
● sandbox-image.service - pull sandbox image defined in containerd config.toml
   Loaded: loaded (/etc/systemd/system/sandbox-image.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2021-12-16 22:21:18 UTC; 1min 58s ago
  Process: 3053 ExecStart=/etc/eks/containerd/pull-sandbox-image.sh (code=exited, status=2)
 Main PID: 3053 (code=exited, status=2)

Dec 16 22:21:18 ip-44-130-26-164 pull-sandbox-image.sh[3053]: github.com/containerd/containerd/vendor/github.com/urfave/cli.Command.Run(0x56302bada9ec, 0x6, 0x0, 0x0, 0x56302c47e... 0x0, ...)
Dec 16 22:21:18 ip-44-130-26-164 pull-sandbox-image.sh[3053]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/com...102 +0xa28
Dec 16 22:21:18 ip-44-130-26-164 pull-sandbox-image.sh[3053]: github.com/containerd/containerd/vendor/github.com/urfave/cli.(*App).Run(0xc00032a380, 0xc0000b8000, 0x9, 0x9, 0x0, 0x0)
Dec 16 22:21:18 ip-44-130-26-164 pull-sandbox-image.sh[3053]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/app...276 +0x7d4
Dec 16 22:21:18 ip-44-130-26-164 pull-sandbox-image.sh[3053]: main.main()
Dec 16 22:21:18 ip-44-130-26-164 pull-sandbox-image.sh[3053]: github.com/containerd/containerd/cmd/ctr/main.go:37 +0x125
Dec 16 22:21:18 ip-44-130-26-164 systemd[1]: sandbox-image.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 16 22:21:18 ip-44-130-26-164 systemd[1]: Failed to start pull sandbox image defined in containerd config.toml.
Dec 16 22:21:18 ip-44-130-26-164 systemd[1]: Unit sandbox-image.service entered failed state.
Dec 16 22:21:18 ip-44-130-26-164 systemd[1]: sandbox-image.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```

on the other hand, the `pull-sandbox-image.sh` is working fine manually.

**Comment by cartermckinnon** [comment]
Can you provide the full stack trace? `journalctl -u sandbox-image`.

**Comment by jihed** [comment]
```Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: Attempt 5 of 5
Dec 16 23:29:35 ip-44-130-26-187 sudo[3671]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/ctr --address=/run/dockershim.sock --namespace k8s.io image pull 602401143452.dkr.ecr.eu-central-1.a
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: Password: panic: provided file is not a console
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: goroutine 1 [running]:
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/vendor/github.com/containerd/console.Current(...)
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/containerd/console/console.go:70
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/cmd/ctr/commands.passwordPrompt(0x0, 0x0, 0x0, 0x0)
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/cmd/ctr/commands/resolver.go:40 +0x3df
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/cmd/ctr/commands.GetResolver(0x563de4d66360, 0xc000337230, 0xc0000af600, 0xc000042070, 0xc0000360b0, 0x563de
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/cmd/ctr/commands/resolver.go:70 +0x3ea
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/cmd/ctr/commands/content.NewFetchConfig(0x563de4d66360, 0xc000337230, 0xc0000af600, 0x0, 0x0, 0x0)
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/cmd/ctr/commands/content/fetch.go:115 +0x5c
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/cmd/ctr/commands/images.glob..func7(0xc0000af600, 0x0, 0x0)
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/cmd/ctr/commands/images/pull.go:81 +0x1d8
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/vendor/github.com/urfave/cli.HandleAction(0x563de4c01e00, 0x563de4d33c70, 0xc0000af600, 0xc0000af600, 0x0)
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/app.go:523 +0xfd
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/vendor/github.com/urfave/cli.Command.Run(0x563de488fcf0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x563de48a7058, 0x1b,
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/command.go:174 +0x58e
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc000328540, 0xc0000af340, 0x0, 0x0)
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/app.go:404 +0x934
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/vendor/github.com/urfave/cli.Command.startApp(0x563de48919ec, 0x6, 0x0, 0x0, 0x563de5235300, 0x2, 0x2, 0x563
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/command.go:329 +0x87f
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/vendor/github.com/urfave/cli.Command.Run(0x563de48919ec, 0x6, 0x0, 0x0, 0x563de5235300, 0x2, 0x2, 0x563de489
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/command.go:102 +0xa28
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/vendor/github.com/urfave/cli.(*App).Run(0xc000328380, 0xc0000b8000, 0x9, 0x9, 0x0, 0x0)
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: /builddir/build/BUILD/containerd-1.4.6-7.amzn2/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/app.go:276 +0x7d4
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: main.main()
Dec 16 23:29:35 ip-44-130-26-187 pull-sandbox-image.sh[3307]: github.com/containerd/containerd/cmd/ctr/main.go:37 +0x125
Dec 16 23:29:35 ip-44-130-26-187 systemd[1]: sandbox-image.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 16 23:29:35 ip-44-130-26-187 systemd[1]: Failed to start pull sandbox image defined in containerd config.toml.
Dec 16 23:29:35 ip-44-130-26-187 systemd[1]: Unit sandbox-image.service entered failed state.
Dec 16 23:29:35 ip-44-130-26-187 systemd[1]: sandbox-image.service failed.
```

**Comment by cartermckinnon** [comment]
This error is probably arising because the `ecr_password` is expected to be passed as part of the `--user` flag, but it doesn't look like it is set correctly. The CLI falls back to accepting the password interactively, and there isn't a terminal attached to the session.

The nature of this error, and the fact that the script works when you execute it manually, indicates this is an issue with your specific modifications and not the AMI. I'm going to close this issue, but feel free to re-open it if you disagree.

**Comment by jihed** [comment]
I fixed by adding  `EnvironmentFile` statement to [sandbox-image.service file](https://github.com/awslabs/amazon-eks-ami/blob/master/files/sandbox-image.service) before running the bootstrap.sh script. like this:

```
sed -i '/Service/a EnvironmentFile=/etc/environment' /etc/eks/containerd/sandbox-image.service

sudo mkdir -p /etc/systemd/system/containerd.service.d
tee <<EOF /etc/systemd/system/containerd.service.d/http-proxy.conf >/dev/null
[Service]
EnvironmentFile=/etc/environment
EOF```

**Comment by jimmyraywv** [comment]
I saw similar behavior with `ami-04635d3effed08298` in ue2. I am using `eksctl` and the config below:
```
    preBootstrapCommands:
      - yum install sysstat -y
      - VERSION="v1.22.0" && curl -L -o crictl-$VERSION-linux-amd64.tar.gz https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz && sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/bin && rm -f crictl-$VERSION-linux-amd64.tar.gz
    ami: ami-04635d3effed08298 #al2
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh log4j \
      --container-runtime containerd
```
