### ISSUE TITLE
Update AMI to include kernel 5.4.191

### ISSUE THREAD

**Issue by gbucknel** [awslabs/amazon-eks-ami#943]
When running Spring 2.6 we are seeing this error in production. 

```
Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298
--
stacktrace | java.io.IOException: Duplicate accept detected. This is a known OS bug. Please consider reporting that you are affected: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1924298 	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:545) 	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:78) 	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129) 	at java.base/java.lang.Thread.run(Unknown Source)
```
The thread linked in the exception indicates there is a kernel fix for this, which has been backported to the LTS kernels. 

5.4.191 includes the fix (https://www.spinics.net/lists/stable-commits/msg244651.html) , https://lwn.net/Articles/892814/

I'm not sure what the usual release cadence is for AMIs, but if you could spin a new one that would be great. 

**Why is this needed**:

We're seeing this error in Production

**Comment by y0zg** [comment]
@cartermckinnon 
Is this included in EKS AMIs?
Seems no.. https://github.com/awslabs/amazon-eks-ami/releases
